import { useEffect, useState } from "react";
import Disclaimer from "./Disclaimer.jsx";
import Icon from "./Icon.jsx";
import { bandMeta, BandPill } from "./BandPill.jsx";

// Printable referral slip. Hidden on screen; @media print rules in
// index.css make it the only visible element when printing.
function ReferralSlip({ result, band }) {
  const clinician = result.clinician;
  return (
    <div id="referral-slip">
      <div style={{ borderBottom: "3px solid #000", paddingBottom: 8, textAlign: "center" }}>
        <h1 style={{ fontSize: 22, fontWeight: 800, letterSpacing: 2 }}>SKINSIGHT</h1>
        <p style={{ fontSize: 13, fontWeight: 600 }}>Referral Information</p>
        <p style={{ fontSize: 10 }}>
          Triage-support prototype · NOT a diagnosis · NOT a medical device
        </p>
      </div>

      <table style={{ width: "100%", marginTop: 12, fontSize: 12 }}>
        <tbody>
          <tr>
            <td style={{ fontWeight: 700, padding: "3px 8px 3px 0", width: 120 }}>Case ID</td>
            <td>CASE-{(result.case_id || "").slice(0, 8).toUpperCase()}</td>
          </tr>
          <tr>
            <td style={{ fontWeight: 700, padding: "3px 8px 3px 0" }}>Printed</td>
            <td>{new Date().toLocaleString()}</td>
          </tr>
        </tbody>
      </table>

      <div style={{ border: "3px solid #000", padding: 12, marginTop: 10 }}>
        <p style={{ fontSize: 24, fontWeight: 800 }}>{result.final_band}</p>
        <p style={{ fontSize: 13 }}>{band.sub}</p>
      </div>

      <h2 style={{ marginTop: 12, fontSize: 14, fontWeight: 700 }}>
        What the patient must do
      </h2>
      <p style={{ fontSize: 15, fontWeight: 700 }}>{result.instruction}</p>

      {clinician && (
        <>
          <h2 style={{ marginTop: 12, fontSize: 14, fontWeight: 700 }}>
            For the receiving clinician (priority {clinician.priority_score}/100)
          </h2>
          <p style={{ fontSize: 13 }}>{clinician.referral}</p>
          {clinician.basis?.length > 0 && (
            <>
              <h2 style={{ marginTop: 10, fontSize: 13, fontWeight: 700 }}>Basis</h2>
              <ul style={{ fontSize: 12, paddingLeft: 18, listStyle: "disc" }}>
                {clinician.basis.map((b) => (
                  <li key={b}>{b}</li>
                ))}
              </ul>
            </>
          )}
        </>
      )}

      {result.safety_explanations?.length > 0 && (
        <>
          <h2 style={{ marginTop: 12, fontSize: 14, fontWeight: 700 }}>
            Why this result
          </h2>
          <ul style={{ fontSize: 12, paddingLeft: 18, listStyle: "disc" }}>
            {result.safety_explanations.map((e) => (
              <li key={e}>{e}</li>
            ))}
          </ul>
        </>
      )}

      {(result.vision || result.history) && (
        <>
          <h2 style={{ marginTop: 12, fontSize: 14, fontWeight: 700 }}>
            Model signals (evidence only — rules decide)
          </h2>
          <p style={{ fontSize: 12 }}>
            {result.vision &&
              `Malignant-group probability: ${(result.vision.malignant_p * 100).toFixed(0)}% · ` +
                `Vision confidence: ${(result.vision.confidence * 100).toFixed(0)}% · `}
            {result.history &&
              `History risk score: ${(result.history.risk_score * 100).toFixed(0)}%`}
          </p>
        </>
      )}

      <div
        style={{
          border: "2px solid #000",
          padding: 8,
          marginTop: 14,
          fontSize: 13,
          fontWeight: 700,
        }}
      >
        {result.disclaimer ||
          "This is not a diagnosis. Only a doctor can tell you what it is."}
      </div>
      <p style={{ marginTop: 8, fontSize: 10, textAlign: "center" }}>
        Generated by SkinSight · Prototype · Not a medical device · Requires
        professional medical assessment
      </p>
    </div>
  );
}

function SignalRow({ label, value, tone }) {
  if (value === null || value === undefined) return null;
  const width = Math.min(Math.max(value, 0), 1) * 100;
  return (
    <div>
      <div className="flex items-baseline justify-between gap-3">
        <span className="text-sm text-ink-secondary">{label}</span>
        <span className="num text-sm font-bold text-ink">{(value * 100).toFixed(0)}%</span>
      </div>
      <div className="mt-1.5 h-1.5 rounded-full bg-surface-muted">
        <div
          className={`h-1.5 rounded-full ${tone || "bg-brand-500"}`}
          style={{ width: `${width}%` }}
        />
      </div>
    </div>
  );
}

export default function ResultCard({ result }) {
  const hasVision = !!result?.vision;
  const [benchmark, setBenchmark] = useState(null);

  // Real, locally-evaluated model benchmark (null = not yet evaluated).
  useEffect(() => {
    if (!hasVision) return;
    fetch("/api/model_info")
      .then((r) => (r.ok ? r.json() : null))
      .then(setBenchmark)
      .catch(() => {});
  }, [hasVision]);

  if (!result?.final_band) return null;
  const band = bandMeta(result.final_band);
  const advisory = result.reasoning?.suggested_band;
  const clinician = result.clinician;
  const visionMetrics = benchmark?.vision?.metrics;
  const imageProvided =
    result.image_provided ??
    !(result.quality_note || "").startsWith("No photograph");

  return (
    <section aria-labelledby="result-heading" className="space-y-4">
      <h2 id="result-heading" className="sr-only">
        Triage result
      </h2>

      {/* 1. FINAL NEXT STEP — hero result card */}
      <div className={`rounded-hero border p-6 shadow-card ${band.bg} ${band.line}`}>
        <p className={`eyebrow !text-current opacity-70 ${band.text}`}>Result</p>
        <div className="mt-2 flex items-center gap-2.5">
          <span className={band.text}>
            <Icon name={band.icon} size={22} />
          </span>
          <span
            className={`inline-flex items-center gap-2 rounded-full border-2 bg-white/70 px-4 py-1 text-lg font-bold tracking-wide ${band.line} ${band.text}`}
          >
            <span className={`h-2 w-2 rounded-full ${band.dot}`} />
            {band.label}
          </span>
        </div>
        <p className={`mt-3 text-sm font-semibold uppercase tracking-[0.06em] ${band.text} opacity-70`}>
          Your recommended next step
        </p>
        <p className={`mt-1 text-xl font-bold leading-snug ${band.text}`}>
          {result.instruction}
        </p>
        <button
          type="button"
          onClick={() => window.print()}
          className="btn-secondary mt-4 h-10"
        >
          <Icon name="printer" size={15} />
          Print referral slip
        </button>
      </div>

      {/* Hidden on screen; the only visible content when printing */}
      <ReferralSlip result={result} band={band} />

      {/* Photograph notices */}
      {result.image_ok === false && imageProvided && (
        <div
          role="alert"
          className="flex items-start gap-2.5 rounded-card border border-review-line bg-review-bg px-4 py-3 text-sm text-review-text"
        >
          <Icon name="camera" size={16} className="mt-0.5 shrink-0" />
          <div>
            <p className="font-semibold">
              The photograph was not used
              {result.quality_note ? `: ${result.quality_note}` : "."}
            </p>
            <p className="mt-0.5">
              This result is based on the patient's answers only. For a
              stronger assessment, retake the photo in good light, hold the
              phone steady, and assess the case again.
            </p>
          </div>
        </div>
      )}
      {result.image_ok === false && !imageProvided && (
        <p className="flex items-start gap-2.5 rounded-card border border-line bg-surface-card px-4 py-3 text-sm text-ink-secondary">
          <Icon name="camera" size={16} className="mt-0.5 shrink-0 text-ink-muted" />
          <span>
            No photograph was provided — this result is based on the patient's
            answers only. Adding a clear photo strengthens the assessment.
          </span>
        </p>
      )}

      {/* 3. IMPORTANT SAFETY INFORMATION */}
      <Disclaimer text={result.disclaimer} />

      {result.safety_triggers?.length > 0 && (
        <div className={`rounded-card border p-4 ${band.line} ${band.bg}`}>
          <p className={`flex items-center gap-2 text-[15px] font-semibold ${band.text}`}>
            <Icon name="alert-triangle" size={16} />
            Important factors
          </p>
          <ul className={`mt-2 space-y-1.5 text-sm ${band.text}`}>
            {(result.safety_explanations?.length
              ? result.safety_explanations
              : result.safety_triggers
            ).map((e) => (
              <li key={e} className="flex gap-2">
                <span className={`mt-2 h-1.5 w-1.5 shrink-0 rounded-full ${band.dot}`} />
                {e}
              </li>
            ))}
          </ul>
          <div className="mt-2.5 flex flex-wrap gap-1.5">
            {result.safety_triggers.map((rule) => (
              <span
                key={rule}
                className={`num rounded-full border bg-white/70 px-2 py-0.5 text-[11px] font-semibold ${band.line} ${band.text}`}
              >
                {rule}
              </span>
            ))}
          </div>
        </div>
      )}
      {(!result.safety_triggers || result.safety_triggers.length === 0) &&
        result.safety_explanations?.length > 0 && (
          <div className="card p-4">
            <p className="eyebrow">Why this result</p>
            <ul className="mt-2 space-y-1.5 text-sm text-ink-secondary">
              {result.safety_explanations.map((e) => (
                <li key={e} className="flex gap-2">
                  <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-ink-muted" />
                  {e}
                </li>
              ))}
            </ul>
          </div>
        )}

      {/* 4. SUPPORTING SIGNALS — grouped */}
      {(result.vision || result.history) && (
        <div className="grid gap-4 sm:grid-cols-2">
          <div className="card p-4">
            <p className="flex items-center gap-2 text-[15px] font-semibold text-ink">
              <Icon name="focus" size={16} className="text-brand-600" />
              Image assessment
            </p>
            {result.vision ? (
              <div className="mt-3 space-y-3">
                <div className="flex items-center justify-between text-sm">
                  <span className="text-ink-secondary">Image quality</span>
                  <span className="flex items-center gap-1.5 font-semibold text-ok-text">
                    <Icon name="check" size={13} strokeWidth={2.2} />
                    Usable
                  </span>
                </div>
                <SignalRow
                  label="Malignant-group probability"
                  value={result.vision.malignant_p}
                  tone="bg-urgent-dot"
                />
                <SignalRow
                  label="Confidence"
                  value={result.vision.confidence}
                  tone="bg-brand-500"
                />
              </div>
            ) : (
              <p className="mt-3 text-sm text-ink-secondary">
                No usable image signal for this case
                {result.quality_note ? ` (${result.quality_note})` : ""}.
              </p>
            )}
          </div>

          <div className="card p-4">
            <p className="flex items-center gap-2 text-[15px] font-semibold text-ink">
              <Icon name="clipboard" size={16} className="text-brand-600" />
              Questionnaire signals
            </p>
            {result.history ? (
              <div className="mt-3 space-y-3">
                <SignalRow
                  label="History risk score"
                  value={result.history.risk_score}
                  tone="bg-review-dot"
                />
                {result.history.red_flags.length > 0 ? (
                  <div>
                    <p className="text-sm text-ink-secondary">Risk indicators</p>
                    <ul className="mt-1 space-y-1 text-sm text-ink">
                      {result.history.red_flags.map((f) => (
                        <li key={f} className="flex gap-2">
                          <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-review-dot" />
                          {f}
                        </li>
                      ))}
                    </ul>
                  </div>
                ) : (
                  <p className="text-sm text-ink-secondary">
                    No history red flags reported.
                  </p>
                )}
                <p className="text-xs text-ink-muted">Source: {result.history.source}</p>
              </div>
            ) : (
              <p className="mt-3 text-sm text-ink-secondary">No history output.</p>
            )}
          </div>
        </div>
      )}

      {result.vision && (
        <p className="text-xs leading-relaxed text-ink-muted">
          {visionMetrics
            ? `Vision model benchmark (HAM10000 lesion-grouped test split): ` +
              `${(visionMetrics.malignant_recall * 100).toFixed(1)}% malignant recall · ` +
              `${(visionMetrics.balanced_accuracy * 100).toFixed(1)}% balanced accuracy. ` +
              `Dermatoscopic benchmark — smartphone photos may differ.`
            : "Vision model benchmark: not yet evaluated on this machine."}{" "}
          Signals are evidence inputs only — the result above is decided by
          the deterministic safety rules.
        </p>
      )}

      {/* Clinician referral recommendation — deterministic templates */}
      {clinician && (
        <div className="card p-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <p className="flex items-center gap-2 text-[15px] font-semibold text-ink">
              <Icon name="stethoscope" size={16} className="text-brand-600" />
              Clinician referral recommendation
            </p>
            <span className="num rounded-full border border-brand-100 bg-brand-50 px-2.5 py-0.5 text-xs font-bold text-brand-700">
              Priority {clinician.priority_score}/100
            </span>
          </div>
          <p className="mt-2 text-sm font-medium leading-relaxed text-ink">
            {clinician.referral}
          </p>
          {clinician.basis?.length > 0 && (
            <div className="mt-2 flex flex-wrap gap-1.5">
              {clinician.basis.map((b) => (
                <span
                  key={b}
                  className="rounded-full border border-line bg-surface-bg px-2.5 py-0.5 text-xs text-ink-secondary"
                >
                  {b}
                </span>
              ))}
            </div>
          )}
          <p className="mt-2 text-xs text-ink-muted">{clinician.note}</p>
        </div>
      )}

      {/* 5. ADVISORY AI EXPLANATION — visually secondary, clearly labeled */}
      {result.reasoning && (
        <div className="rounded-card border border-line bg-surface-muted p-4">
          <div className="flex flex-wrap items-center justify-between gap-2">
            <p className="text-sm font-semibold text-ink-secondary">
              Advisory explanation
            </p>
            <span className="rounded-full border border-line-strong bg-surface-card px-2 py-0.5 text-[11px] font-bold uppercase tracking-[0.06em] text-ink-muted">
              Advisory only
            </span>
          </div>
          <p className="mt-1 text-xs text-ink-muted">
            AI-generated supporting context. It does not override the
            assessment result above.
          </p>
          <p className="mt-2 text-sm leading-relaxed text-ink-secondary">
            {result.reasoning.rationale}
          </p>
          {advisory && advisory !== result.final_band && (
            <p className="mt-2 text-xs text-ink-muted">
              The model suggested <strong>{advisory}</strong>; the deterministic
              safety engine decided <strong>{result.final_band}</strong>.
            </p>
          )}
        </div>
      )}
      {!result.reasoning && (
        <div className="rounded-card border border-line bg-surface-muted p-4 text-sm leading-relaxed text-ink-secondary">
          The explanation model was unavailable, so the case was automatically
          treated with extra caution (rule R8).
        </div>
      )}

      {/* 6. TECHNICAL DETAILS — collapsible */}
      <details className="card p-4">
        <summary className="flex cursor-pointer items-center gap-2 text-sm font-semibold text-ink-secondary transition-colors duration-150 hover:text-ink">
          <Icon name="chevron-down" size={14} className="text-ink-muted" />
          View technical details
        </summary>
        <div className="mt-3 space-y-4 text-sm text-ink-secondary">
          {result.vision ? (
            <div>
              <p className="eyebrow mb-2">Image model</p>
              <p>
                Malignant-group probability:{" "}
                <span className="num font-semibold text-ink">
                  {result.vision.malignant_p.toFixed(3)}
                </span>{" "}
                · Confidence:{" "}
                <span className="num font-semibold text-ink">
                  {result.vision.confidence.toFixed(3)}
                </span>
              </p>
              <ul className="mt-2 space-y-1.5">
                {Object.entries(result.vision.probs)
                  .sort(([, a], [, b]) => b - a)
                  .map(([cls, p]) => (
                    <li key={cls} className="flex items-center gap-2">
                      <span className="num w-12 text-xs text-ink-muted">{cls}</span>
                      <div className="h-1.5 flex-1 rounded-full bg-surface-muted">
                        <div
                          className="h-1.5 rounded-full bg-brand-500"
                          style={{ width: `${Math.min(Number(p) * 100, 100)}%` }}
                        />
                      </div>
                      <span className="num w-12 text-right text-xs">
                        {(Number(p) * 100).toFixed(1)}%
                      </span>
                    </li>
                  ))}
              </ul>
              {result.vision.gradcam_path && (
                <img
                  src={result.vision.gradcam_path}
                  alt="Grad-CAM heatmap showing image regions that most influenced the model"
                  className="mt-2 max-h-64 rounded-xl border border-line"
                />
              )}
            </div>
          ) : (
            <p>
              Image model output: not available for this case
              {result.quality_note ? ` (${result.quality_note})` : ""}.
            </p>
          )}

          {result.reasoning?.abcde && (
            <div>
              <p className="eyebrow mb-2">ABCDE explanation (generated)</p>
              <ul className="space-y-1">
                {Object.entries(result.reasoning.abcde).map(([k, v]) => (
                  <li key={k}>
                    <strong className="text-ink">{k}:</strong> {v}
                  </li>
                ))}
              </ul>
            </div>
          )}

          <div>
            <p className="eyebrow mb-1">Case</p>
            <p className="num text-xs">{result.case_id}</p>
            {result.final_band && (
              <p className="mt-1.5">
                <BandPill band={result.final_band} />
              </p>
            )}
          </div>
        </div>
      </details>
    </section>
  );
}
